# Site settings
title: Anish Kasi
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anish Kasi
user_description: Second year Computer Science Student at PES University. A blockchain enthusiast and a passionate Web Developer.
user_title: Software Developer
email: anishkasi@gmail.com
github_username:  anishkasi

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
